service: cart-service
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: get
          path: /
      - http:
          method: get
          path: ping
      - http:
          method: get
          path: /api/profile/cart
          cors: true
          request:
            parameters:
              querystrings:
                userId: true
          