service: cart-service
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: get
          path: /
      - http:
          method: get
          path: ping